### PR TITLE
Closes #13

### LINKED ISSUE #13: Allow a template's theme hook to be changed.

### PR DESCRIPTION
**Pull request by tsteiner**
#13

Do this after #9 and #11

### CODE REVIEW

**Comment by tsteiner** [comment]
I'm just following the file naming convention: you can have both a node--policy.tpl.php and node__polity.tpl.php.

**Comment by ericras** [comment]
You could have the file node__policy.tpl.php but I don't believe it's examined is it?

**Comment by tsteiner** [comment]
As far as I can tell, the only filter is /.tpl.php$/
It then replaces any - with _ to create the theme hook name.
See https://api.drupal.org/api/drupal/includes%21theme.inc/function/drupal_find_theme_templates/7

**Comment by ericras** [comment]
Nope, node__policy.tpl.php doesn't work, just tested it

**Comment by ericras** [comment]
https://github.com/tsteiner/tims/pull/1

**Comment by tsteiner** [comment]
Ah, there's one place where they change file names from - to _ and another where they change hook names from _ to -

**Comment by ericras** [comment]
Works, I thought maybe leaving tims_get_templates() abstracted made sense but probably not neccessary

**Comment by tsteiner** [comment]
I only added it to handle the - to _ thing, so I just figured I'd go back to the original code.

**Pull request merged**
