### PR TITLE
Closes #15

### LINKED ISSUE #15: Enable syntax hilighting in the editor
The ACE editor has support for TWIG.

### PR DESCRIPTION
**Pull request by tsteiner**
#15

### CODE REVIEW

**Comment by ericras** [comment]
Using /vendor and a submoduel is problem for releasing as a general non-unl specific project.

Possibly include the library in the UNL-CMS project and leave this general with instructions to install in sites/all/libraries ?

Plus, as far as UNL-CMS goes, we do have Code Mirror in there already

**Comment by tsteiner** [comment]
Does code mirror support TWIG?

**Comment by ericras** [comment]
Hmm, good question - just figured it would.

https://github.com/marijnh/CodeMirror/issues/103
http://codemirror.net/demo/mustache.html

**Comment by ericras** [comment]
Replace ACE with CodeMirror: https://github.com/unlcms/tims/pull/17

**Pull request merged**
